In [3]:
import pandas as pd
import numpy as np

In [ ]:
# 1. who is the top-performing salesperson per region.

data = {
    'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West'],
    'Salesperson': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Heidi'],
    'Product': ['A', 'A', 'B', 'B', 'A', 'B', 'A', 'B'],
    'Revenue': [1200, 1500, 800, 950, 1100, 1300, 1000, 1050]
}
df = pd.DataFrame(data)

# step 1
grouped = df.groupby(['Region', 'Salesperson'])['Revenue'].sum().reset_index()
print(grouped)

# step 2
grouped.sort_values(['Region', 'Revenue'], ascending=[True, False]).groupby(['Region']).first()

  Region Salesperson  Revenue
0   East     Charlie      800
1   East       Grace     1000
2  North       Alice     1200
3  North         Eve     1100
4  South         Bob     1500
5  South       Frank     1300
6   West       David      950
7   West       Heidi     1050

       Salesperson  Revenue
Region
East         Grace     1000
North        Alice     1200
South          Bob     1500
West         Heidi     1050

In [ ]:
# 2. what is the top performing product per region

data = {
    'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West'],
    'Salesperson': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Heidi'],
    'Product': ['A', 'A', 'B', 'B', 'A', 'B', 'A', 'B'],
    'Revenue': [1200, 1500, 800, 950, 1100, 1300, 1000, 1050]
}
df = pd.DataFrame(data)
display(df)

# step 1
grouped = df.groupby(['Region', 'Product'])['Revenue'].sum().reset_index()
display(grouped)

# step 2
grouped.sort_values(['Region', 'Revenue'], ascending=[True, False]).groupby('Region').first()

  Region Salesperson Product  Revenue
0  North       Alice       A     1200
1  South         Bob       A     1500
2   East     Charlie       B      800
3   West       David       B      950
4  North         Eve       A     1100
5  South       Frank       B     1300
6   East       Grace       A     1000
7   West       Heidi       B     1050

  Region Product  Revenue
0   East       A     1000
1   East       B      800
2  North       A     2300
3  South       A     1500
4  South       B     1300
5   West       B     2000

'\n'

       Product  Revenue
Region
East         A     1000
North        A     2300
South        A     1500
West         B     2000

In [12]:
# 3. compute multiple aggregations like mean, sum, and count per group using pandas.groupby
#### Compute the mean, sum, and count of Revenue per Region.

# Sample sales data
data = {
    'Region': ['North', 'South', 'North', 'East', 'South', 'East', 'North'],
    'Salesperson': ['Alice', 'Bob', 'Alice', 'Charlie', 'Bob', 'Charlie', 'Eve'],
    'Revenue': [200, 150, 300, 400, 250, 100, 500]
}

df = pd.DataFrame(data)

df.groupby('Region')['Revenue'].agg(['mean','sum', 'count'])

              mean   sum  count
Region
East    250.000000   500      2
North   333.333333  1000      3
South   200.000000   400      2

In [ ]:
# 4. join the dataframes

# Customer information
customers = pd.DataFrame({
    'CustomerID': [101, 102, 103, 104],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'City': ['Pune', 'Delhi', 'Mumbai', 'Chennai']
    }
    )

display(customers)
# Order information
orders = pd.DataFrame({
    'OrderID': [1001, 1002, 1003, 1004, 1005],
    'CustomerID': [101, 102, 101, 105, 103],
    'Amount': [250, 450, 300, 500, 150]
})

display(orders)
display(pd.merge(customers, orders, 
         on = 'CustomerID', how='outer'))

display(pd.merge(customers, orders, 
         on = 'CustomerID', how='inner'))

   CustomerID     Name     City
0         101    Alice     Pune
1         102      Bob    Delhi
2         103  Charlie   Mumbai
3         104    David  Chennai

   OrderID  CustomerID  Amount
0     1001         101     250
1     1002         102     450
2     1003         101     300
3     1004         105     500
4     1005         103     150

   CustomerID     Name     City  OrderID  Amount
0         101    Alice     Pune   1001.0   250.0
1         101    Alice     Pune   1003.0   300.0
2         102      Bob    Delhi   1002.0   450.0
3         103  Charlie   Mumbai   1005.0   150.0
4         104    David  Chennai      NaN     NaN
5         105      NaN      NaN   1004.0   500.0

   CustomerID     Name    City  OrderID  Amount
0         101    Alice    Pune     1001     250
1         101    Alice    Pune     1003     300
2         102      Bob   Delhi     1002     450
3         103  Charlie  Mumbai     1005     150